name: nmls
description: "Learning Management System."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.3.0
  google_mobile_ads: ^6.0.0
  provider: ^6.1.5+1
  firebase_core: ^4.1.1
  table_calendar: ^3.2.0
  cloud_firestore: ^6.0.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.0
  google_sign_in: ^7.2.0
  font_awesome_flutter: ^10.10.0
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.3
  app_links: ^6.4.1
  fl_chart: ^1.1.1
  pie_chart: ^5.4.0
  flutter_chat_ui: ^2.9.0
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  flutter_chat_core: ^2.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
