// in models.dart
import 'package:hive/hive.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

part 'models.g.dart'; // This will be generated by build_runner

// --- STUDENT MODEL ---
@HiveType(typeId: 0)
class Student extends HiveObject {
  @HiveField(0)
  final String id;
  @HiveField(1)
  final String name;
  @HiveField(2)
  final String email;

  Student({required this.id, required this.name, required this.email});

  factory Student.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return Student(
      id: doc.id,
      name: data['name'] ?? 'Unknown Student',
      email: data['email'] ?? 'No Email',
    );
  }
}

// --- ACADEMIC RECORD MODEL ---
@HiveType(typeId: 1)
class AcademicRecord extends HiveObject {
  @HiveField(0)
  final String courseTitle;
  @HiveField(1)
  final String courseCode;
  @HiveField(2)
  final String grade;
  @HiveField(3)
  final DateTime enrollmentDate;
  @HiveField(4)
  final String lecturerName;

  AcademicRecord({
    required this.courseTitle,
    required this.courseCode,
    required this.grade,
    required this.enrollmentDate,
    required this.lecturerName,
  });
}

// --- LECTURER & SCHOOL ADMIN (Placeholders) ---
// These don't need to be cached for this example, but should live with your models.
class Lecturer {
  final String id;
  final String name;
  Lecturer({required this.id, required this.name});
}

class SchoolAdmin {
  final String id;
  final String name;
  SchoolAdmin({required this.id, required this.name});
}
